<?php

return [
    [
        'slug'        => '2026-phone-case',
        'name'        => '2026 Phone Case Designs',
        'price'       => 19.99,
        'price_mxn'   => 339.99,
        'icon'        => '📱',
        'category'    => 'phone-cases',
        'description' => 'Protect your phone in style with our brand new 2026 designs. Premium polycarbonate shell with soft TPU inner lining.',
        'models'      => ['iPhone 16 Pro Max', 'iPhone 16 Pro', 'iPhone 16', 'iPhone 15 Pro', 'iPhone 15', 'Samsung S24 Ultra', 'Samsung S24', 'Samsung S23'],
        'eta'         => 'Arriving in 2-8 weeks',
        'image'       => null,
        'new'         => true,
    ],
    [
        'slug'        => 'phone-cases',
        'name'        => 'Phone Cases',
        'price'       => 24.99,
        'price_mxn'   => 424.99,
        'icon'        => '📱',
        'category'    => 'phone-cases',
        'description' => 'Classic Kittfill illustrated phone cases featuring original character art. Hard-shell design with glossy finish.',
        'models'      => ['iPhone 16 Pro Max', 'iPhone 16 Pro', 'iPhone 16', 'iPhone 15 Pro', 'iPhone 15', 'Samsung S24 Ultra', 'Samsung S24', 'Samsung S23'],
        'eta'         => 'Arriving in 2-8 weeks',
        'image'       => null,
        'new'         => true,
    ],
    [
        'slug'        => 'custom-sona-hoodie',
        'name'        => 'Custom Sona Hoodie',
        'price'       => 59.99,
        'price_mxn'   => 1019.99,
        'icon'        => '👕',
        'category'    => 'hoodies',
        'description' => 'Ultra-soft fleece hoodie with your custom Sona character printed on the back. Unisex fit, pre-shrunk cotton blend.',
        'models'      => ['S', 'M', 'L', 'XL', 'XXL'],
        'eta'         => 'Arriving in 3-5 weeks',
        'image'       => null,
        'new'         => true,
    ],
    [
        'slug'        => 'full-res-wallpaper',
        'name'        => 'Full Res Wallpaper',
        'price'       => 9.99,
        'price_mxn'   => 169.99,
        'icon'        => '🖼️',
        'category'    => 'wallpapers',
        'description' => 'High-resolution digital wallpaper pack for desktop and mobile. Includes 5 exclusive Kittfill illustrations.',
        'models'      => ['Desktop (4K)', 'Desktop (1440p)', 'Mobile (iPhone)', 'Mobile (Android)'],
        'eta'         => 'Instant delivery via e-mail',
        'image'       => null,
        'new'         => false,
    ],
    [
        'slug'        => 'tqm-sticker',
        'name'        => 'TQM Sticker',
        'price'       => 5.99,
        'price_mxn'   => 101.99,
        'icon'        => '🎨',
        'category'    => 'stickers',
        'description' => '"Te Quiero Mucho" vinyl sticker. Waterproof and UV-resistant, perfect for laptops, bottles, and notebooks.',
        'models'      => ['Small (5cm)', 'Medium (8cm)', 'Large (12cm)'],
        'eta'         => 'Arriving in 2-4 weeks',
        'image'       => null,
        'new'         => false,
    ],
    [
        'slug'        => 'buttercat-cap',
        'name'        => 'Buttercat Cap',
        'price'       => 29.99,
        'price_mxn'   => 509.99,
        'icon'        => '🧢',
        'category'    => 'caps',
        'description' => 'Embroidered Buttercat design on a structured 6-panel cap. Adjustable snapback closure.',
        'models'      => ['One Size', 'S/M', 'L/XL'],
        'eta'         => 'Arriving in 2-4 weeks',
        'image'       => null,
        'new'         => false,
    ],
    [
        'slug'        => 'pondering-sticker',
        'name'        => 'Pondering Sticker',
        'price'       => 5.99,
        'price_mxn'   => 101.99,
        'icon'        => '✨',
        'category'    => 'stickers',
        'description' => 'The iconic "Pondering" cat illustration as a holographic vinyl sticker. Water and scratch resistant.',
        'models'      => ['Small (5cm)', 'Medium (8cm)', 'Large (12cm)'],
        'eta'         => 'Arriving in 2-4 weeks',
        'image'       => null,
        'new'         => false,
    ],
    [
        'slug'        => 'kittfill-tee',
        'name'        => 'Kittfill Classic Tee',
        'price'       => 34.99,
        'price_mxn'   => 594.99,
        'icon'        => '👚',
        'category'    => 'apparel',
        'description' => 'Soft ring-spun cotton tee with the Kittfill logo on the front. Regular fit, double-needle stitching.',
        'models'      => ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
        'eta'         => 'Arriving in 2-4 weeks',
        'image'       => null,
        'new'         => false,
    ],
    [
        'slug'        => 'fan-pack',
        'name'        => 'Fan Pack Bundle',
        'price'       => 49.99,
        'price_mxn'   => 849.99,
        'icon'        => '🎁',
        'category'    => 'bundles',
        'description' => 'The ultimate Kittfill fan bundle: includes 1 tee, 3 stickers, and 1 wallpaper pack. Save 20% vs buying separately!',
        'models'      => ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
        'eta'         => 'Arriving in 3-5 weeks',
        'image'       => null,
        'new'         => false,
    ],
    [
        'slug'        => 'kittfill-tote-bag',
        'name'        => 'Kittfill Tote Bag',
        'price'       => 22.99,
        'price_mxn'   => 390.99,
        'icon'        => '👜',
        'category'    => 'accessories',
        'description' => 'Heavy-duty canvas tote bag with an all-over Kittfill print. Perfect for groceries, books, or everyday carry.',
        'models'      => ['Standard'],
        'eta'         => 'Arriving in 2-4 weeks',
        'image'       => null,
        'new'         => true,
    ],
    [
        'slug'        => 'dreamy-cat-poster',
        'name'        => 'Dreamy Cat Poster',
        'price'       => 14.99,
        'price_mxn'   => 254.99,
        'icon'        => '🖼️',
        'category'    => 'wallpapers',
        'description' => 'Museum-quality matte poster print of the "Dreamy Cat" illustration. Printed on 200gsm archival paper.',
        'models'      => ['A4 (21×30cm)', 'A3 (30×42cm)', 'A2 (42×59cm)'],
        'eta'         => 'Arriving in 2-4 weeks',
        'image'       => null,
        'new'         => true,
    ],
    [
        'slug'        => 'kittfill-enamel-pin',
        'name'        => 'Kittfill Enamel Pin',
        'price'       => 12.99,
        'price_mxn'   => 220.99,
        'icon'        => '📌',
        'category'    => 'accessories',
        'description' => 'Hard enamel pin featuring the Kittfill mascot. Gold-plated with butterfly clutch backing. Approximately 3cm.',
        'models'      => ['Standard'],
        'eta'         => 'Arriving in 2-4 weeks',
        'image'       => null,
        'new'         => true,
    ],
];
